# Generated by Django 3.1.4 on 2021-07-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210728_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='listing_id',
            field=models.IntegerField(default=0),
        ),
    ]
