# Generated by Django 3.1.4 on 2021-07-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210728_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='listing_id',
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
