# Generated by Django 4.1.1 on 2022-10-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0017_alter_listing_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(
                blank=True,
                default="",
                upload_to="C:\\Users\\Giannis\\Desktop\\HarvardCS\\Projects\\commerce\\media",
            ),
        ),
    ]
