# Generated by Django 4.1.1 on 2022-10-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0023_alter_listing_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(
                default="C:\\Users\\Giannis\\Desktop\\HarvardCS\\Projects\\commerce\\default-placeholder-image.jpg",
                upload_to="img",
            ),
        ),
    ]
